services:
    semaphore_db:
        image: postgres
        environment:
            POSTGRES_USER: semaphore
            POSTGRES_PASSWORD: ltl5b7vlkm
            POSTGRES_DB: semaphore
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:latest
        environment:
            SEMAPHORE_DB_DIALECT: postgres
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: ltl5b7vlkm
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: 123456
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
        volumes:
            - semaphore_data:/var/lib/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
networks:
    semaphore_network: {driver: "bridge"}